### ISSUE TITLE
Карточка в ИПЛ

### ISSUE THREAD

**Issue by ConstantineEpifanov** [Alfa-PDP/frontend#9]
Создание карточки сотрудника, его прогресса, а так же блока с описанием мотивации сотрудника

![Image](https://github.com/Alfa-PDP/frontend/assets/113720033/911374e2-91e8-4005-9d26-8953b9e8970d)

**Comment by SenpaiSun** [comment]
Готово, добавлена карточка сотрудника, атрибуты сотрудника с реализованной логикой и анимацией
